<a href="https://colab.research.google.com/github/Parkseoho/DAStudy-sun2/blob/main/SEOHO/2024_03_03_%ED%95%AD%EA%B3%B5%EC%82%AC%EB%8D%B0%EC%9D%B4%ED%84%B0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Airline Dataset Updated - v2.csv',encoding='utf-8')

### 칼럼 설명
- Passenger ID - 각 승객의 고유 식별자
- First Name - 승객의 이름
- Last Name - 승객의 성
- Gender - 성별
- Age - 나이
- Nationality - 국적
- Airport Name - 공항명
- Airport Country Code - 공항 국가 코드
- Country Name - 공항의 국가명
- Airport Continent - 공항이 위치한 대륙
- Continents - 비행 경로에 포함된 대륙
- Departure Date - 출발 날짜
- Arrival Airport - 도착 공항명
- Pilot Name - 조종사 이름
- Flight Status - 항공편의 상태 (정시, 지연, 취소 등)

In [ ]:
# Age 칼럼 제외 모든 칼럼 object Type

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98619 entries, 0 to 98618
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Passenger ID          98619 non-null  object
 1   First Name            98619 non-null  object
 2   Last Name             98619 non-null  object
 3   Gender                98619 non-null  object
 4   Age                   98619 non-null  int64
 5   Nationality           98619 non-null  object
 6   Airport Name          98619 non-null  object
 7   Airport Country Code  98619 non-null  object
 8   Country Name          98619 non-null  object
 9   Airport Continent     98619 non-null  object
 10  Continents            98619 non-null  object
 11  Departure Date        98619 non-null  object
 12  Arrival Airport       98619 non-null  object
 13  Pilot Name            98619 non-null  object
 14  Flight Status         98619 non-null  object
dtypes: int64(1), object(14)
memory usage: 11.3+ MB

In [ ]:
df.nunique()

Passenger ID            98619
First Name               8437
Last Name               41658
Gender                      2
Age                        90
Nationality               240
Airport Name             9062
Airport Country Code      235
Country Name              235
Airport Continent           6
Continents                  6
Departure Date            364
Arrival Airport          9024
Pilot Name              98605
Flight Status               3
dtype: int64

In [ ]:
# Age 변환

In [ ]:
ad = ((df.nunique()<400)*1).reset_index()
for i in list(ad[ad[0]>0]['index'].values):
    print(i)
    print(df[i].value_counts(normalize=True).reset_index())
    print()

Gender
    index    Gender
0    Male  0.502925
1  Female  0.497075

Age
    index       Age
0      29  0.011864
1      27  0.011803
2      39  0.011712
3      46  0.011671
4       6  0.011641
..    ...       ...
85     16  0.010667
86     31  0.010647
87     71  0.010637
88     68  0.010596
89     34  0.010505

[90 rows x 2 columns]

Nationality
                      index  Nationality
0                     China     0.185735
1                 Indonesia     0.107069
2                    Russia     0.057727
3               Philippines     0.053124
4                    Brazil     0.038441
..                      ...          ...
235                 Romania     0.000020
236  British Virgin Islands     0.000020
237                  Jersey     0.000010
238          Norfolk Island     0.000010
239            Sint Maarten     0.000010

[240 rows x 2 columns]

Airport Country Code
    index  Airport Country Code
0      US              0.224135
1      AU              0.064592
2      CA              0.055000
3      BR              0.045671
4      PG              0.041381
..    ...                   ...
230    AD              0.000071
231    MC              0.000071
232    NR              0.000071
233    PW              0.000051
234    JE              0.000041

[235 rows x 2 columns]

Country Name
                index  Country Name
0       United States      0.224135
1           Australia      0.064592
2              Canada      0.055000
3              Brazil      0.045671
4    Papua New Guinea      0.041381
..                ...           ...
230           Andorra      0.000071
231            Monaco      0.000071
232             Nauru      0.000071
233             Palau      0.000051
234            Jersey      0.000041

[235 rows x 2 columns]

Airport Continent
  index  Airport Continent
0   NAM           0.324816
1    AS           0.188980
2    OC           0.140602
3    EU           0.125077
4    AF           0.111845
5   SAM           0.108681

Continents
           index  Continents
0  North America    0.324816
1           Asia    0.188980
2        Oceania    0.140602
3         Europe    0.125077
4         Africa    0.111845
5  South America    0.108681

Departure Date
          index  Departure Date
0     7/22/2022        0.003296
1     5/26/2022        0.003184
2    10/16/2022        0.003143
3     8/15/2022        0.003143
4    11/25/2022        0.003143
..          ...             ...
359  12-12-2022        0.002363
360   4/30/2022        0.002363
361   8/28/2022        0.002352
362  10-04-2022        0.002342
363   6/18/2022        0.002271

[364 rows x 2 columns]

Flight Status
       index  Flight Status
0  Cancelled       0.334033
1    On Time       0.333060
2    Delayed       0.332907

In [ ]:
a = ['Nationality','Airport Name','Country Name','Arrival Airport','Pilot Name']

In [ ]:
df_Nationality =df[['Nationality','Flight Status']].value_counts().reset_index()
df_Nationality['total'] = ''
for i in df_Nationality['Nationality'].unique():
    df_Nationality.loc[df_Nationality['Nationality']==i,'total'] = df_Nationality.loc[df_Nationality['Nationality']==i][0].sum()
df_Nationality['rate'] = df_Nationality[0]/df_Nationality['total']

In [ ]:
df_Nationality[df_Nationality[0]>=30].sort_values('rate',ascending=False)

      Nationality Flight Status   0 total      rate
277  Burkina Faso     Cancelled  38    84  0.452381
327    Micronesia       On Time  30    69  0.434783
256      Zimbabwe       On Time  45   104  0.432692
227         Haiti     Cancelled  55   128  0.429688
309        Gambia     Cancelled  33    79  0.417722
..            ...           ...  ..   ...       ...
191       Tunisia       On Time  72   269  0.267658
243        Latvia     Cancelled  49   190  0.257895
210    Madagascar       Delayed  62   242  0.256198
295     Sri Lanka       On Time  35   138  0.253623
214    Bangladesh       On Time  61   244      0.25

[328 rows x 5 columns]

In [ ]:
df_Nationality[df_Nationality[0]>=30].sort_values(['Flight Status','rate'],ascending=[True,False]).head(20)

               Nationality Flight Status    0 total      rate
277           Burkina Faso     Cancelled   38    84  0.452381
227                  Haiti     Cancelled   55   128  0.429688
309                 Gambia     Cancelled   33    79  0.417722
319                  Sudan     Cancelled   31    76  0.407895
250            El Salvador     Cancelled   47   116  0.405172
228                  Italy     Cancelled   55   136  0.404412
162             Madagascar     Cancelled   94   242   0.38843
163             Bangladesh     Cancelled   94   244  0.385246
293                 Kosovo     Cancelled   35    91  0.384615
244                Uruguay     Cancelled   49   129  0.379845
303                   Chad     Cancelled   33    87   0.37931
152                Tunisia     Cancelled  102   269  0.379182
71                 Croatia     Cancelled  190   508  0.374016
325                 Angola     Cancelled   30    81   0.37037
246             Tajikistan     Cancelled   48   130  0.369231
181                 Uganda     Cancelled   78   212  0.367925
192             Uzbekistan     Cancelled   72   196  0.367347
110             Kazakhstan     Cancelled  136   372  0.365591
99   Palestinian Territory     Cancelled  145   398  0.364322
207         United Kingdom     Cancelled   65   179  0.363128

In [ ]:
df_Nationality[df_Nationality[0]>=30].sort_values(['Flight Status','rate'],ascending=[False,False]).head(20)

      Nationality Flight Status    0 total      rate
327    Micronesia       On Time   30    69  0.434783
256      Zimbabwe       On Time   45   104  0.432692
229        Jordan       On Time   54   132  0.409091
285       Moldova       On Time   36    92  0.391304
104      Tanzania       On Time  143   373  0.383378
233         Italy       On Time   52   136  0.382353
90        Ireland       On Time  157   412  0.381068
188    Costa Rica       On Time   73   193  0.378238
259     Mauritius       On Time   43   115  0.373913
260       Jamaica       On Time   43   115  0.373913
299    Kyrgyzstan       On Time   34    91  0.373626
300       Comoros       On Time   34    91  0.373626
290  Sierra Leone       On Time   36    97  0.371134
157    Azerbaijan       On Time   95   257   0.36965
199        Latvia       On Time   70   190  0.368421
305         Niger       On Time   33    90  0.366667
93       Mongolia       On Time  152   420  0.361905
316        Zambia       On Time   31    86  0.360465
100         Yemen       On Time  144   400      0.36
175        Panama       On Time   82   228  0.359649

In [ ]:
# a = ['Nationality','Airport Name','Country Name','Arrival Airport','Pilot Name']
# for i in a:
#     globals()['df_{}'.format(i)] =df[[i,'Flight Status']].value_counts().reset_index()
#     globals()['df_{}'.format(i)] ['total'] = ''
#     for s in globals()['df_{}'.format(i)][i].unique():
#         globals()['df_{}'.format(i)].loc[globals()['df_{}'.format(i)][i]==s,'total'] = globals()['df_{}'.format(i)].loc[globals()['df_{}'.format(i)][i]==s][0].sum()
#     globals()['df_{}'.format(i)]['rate'] =globals()['df_{}'.format(i)][0]/globals()['df_{}'.format(i)]['total']

In [ ]:
df_Airport  =df[['Airport Name','Flight Status']].value_counts().reset_index()
df_Airport['total'] = ''
for i in df_Airport['Airport Name'].unique():
    df_Airport.loc[df_Airport['Airport Name']==i,'total'] = df_Airport.loc[df_Airport['Airport Name']==i][0].sum()
df_Airport['rate'] = df_Airport[0]/df_Airport['total']

In [ ]:
df_Airport[0].mean()

3.7293525941612464

In [ ]:
df_Airport.sort_values(['Flight Status','rate'],ascending=[True,False]).head(20)

,Airport Name,Flight Status,0,total,rate
8617,Nova Vida Airport,Cancelled,4,4,1.0
13458,Uvol Airport,Cancelled,3,3,1.0
14127,Savannah Hilton Head International Airport,Cancelled,3,3,1.0
20428,Mount Gambier Airport,Cancelled,2,2,1.0
23948,Hiroshima Airport,Cancelled,1,1,1.0
26339,Falcon State Airport,Cancelled,1,1,1.0
1930,General Ulpiano Paez Airport,Cancelled,7,8,0.875
2304,Guna Airport,Cancelled,6,7,0.857143
2477,Rafael Nuñez International Airport,Cancelled,6,7,0.857143
2792,Francisco Beltrão Airport,Cancelled,6,7,0.857143
3361,Cordillo Downs Airport,Cancelled,6,7,0.857143
3501,Kupiano Airport,Cancelled,6,7,0.857143
3565,Kaduna Airport,Cancelled,6,7,0.857143
4478,Nanyang Jiangying Airport,Cancelled,5,6,0.833333
4581,Kamileroi Airport,Cancelled,5,6,0.833333
4867,Phnom Penh International Airport,Cancelled,5,6,0.833333
4923,Emerald Airport,Cancelled,5,6,0.833333
7434,Calgary International Airport,Cancelled,5,6,0.833333
7743,Viru Viru International Airport,Cancelled,5,6,0.833333
7848,Cacoal Airport,Cancelled,5,6,0.833333

In [ ]:
df_Airport.sort_values(['Flight Status','rate'],ascending=[False,False]).head(20)

                     Airport Name Flight Status   0 total      rate
1469    Circle City /New/ Airport       On Time   7     7       1.0
1499       Brighton Downs Airport       On Time   7     7       1.0
10945       Buon Ma Thuot Airport       On Time   4     4       1.0
21494    Balıkesir Merkez Airport       On Time   2     2       1.0
155    Sivas Nuri Demirağ Airport       On Time  10    11  0.909091
2135                Pärnu Airport       On Time   6     7  0.857143
2377   Cape Romanzof LRRS Airport       On Time   6     7  0.857143
3327           La Romaine Airport       On Time   6     7  0.857143
3615     Minami Torishima Airport       On Time   6     7  0.857143
156              Dong Hoi Airport       On Time  10    12  0.833333
4826                 Axum Airport       On Time   5     6  0.833333
4868            Shubuling Airport       On Time   5     6  0.833333
5380              Quaqtaq Airport       On Time   5     6  0.833333
5888       Annette Island Airport       On Time   5     6  0.833333
7176          Uru Harbour Airport       On Time   5     6  0.833333
7244               Tagula Airport       On Time   5     6  0.833333
7258        Offutt Air Force Base       On Time   5     6  0.833333
261     Melchor de Mencos Airport       On Time   9    11  0.818182
414               Kaimana Airport       On Time   8    10       0.8
510                   Mal Airport       On Time   8    10       0.8

In [ ]:
df_Pilot  =df[['Pilot Name','Flight Status']].value_counts().reset_index()
df_Pilot['total'] = ''
for i in df_Pilot['Pilot Name'].unique():
    df_Pilot.loc[df_Pilot['Pilot Name']==i,'total'] = df_Pilot.loc[df_Pilot['Pilot Name']==i][0].sum()
df_Pilot['rate'] = df_Pilot[0]/df_Pilot['total']

In [ ]:
df_Pilot.sort_values(['Pilot Name','rate'],ascending=[True,False]).head(20)

In [ ]:
df_Pilot.sort_values(['Pilot Name','rate'],ascending=[False,False]).head(20)

In [ ]:
df_Pilot[0].mean()